/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.registroInicioSesion;

import co.edu.unicauca.mvc.vistas.adminConferencia.VtnPrincipalAdmin;
import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoUsuarios;
import co.edu.unicauca.mvc.utilidades.Utilidades;
import javax.swing.border.MatteBorder;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Dark
 */
public class VtnPrincipalLogin extends javax.swing.JFrame {

    private ServicioAlmacenamientoUsuarios objServAlmacUsuarios;
    private VtnPrincipalSignUp objVtnPrincipalSignUp;

    /**
     * Creates new form VtnPrincipalLogin1
     */
    public VtnPrincipalLogin() {
        initComponents();
        MatteBorder bordeInferior = new MatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY);
        jTextFieldUsuario.setBorder(bordeInferior);
        jTextFieldPassword.setBorder(bordeInferior);
    }

    public void asociarServiciosAlmacenamiento(
            ServicioAlmacenamientoUsuarios objServicio) {
        this.objServAlmacUsuarios = objServicio;
    }

    public void asociarServicoAlmacenamientoUsuarios(ServicioAlmacenamientoUsuarios objServicio) {
        this.objServAlmacUsuarios = objServicio;
        relacionarInternalFrameConJdesptokPane();
    }

    private void relacionarInternalFrameConJdesptokPane() {
        this.objVtnPrincipalSignUp = new VtnPrincipalSignUp(this.objServAlmacUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNoCuenta = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelIniciarSesion.setFont(new java.awt.Font("Roboto Thin", 0, 36)); // NOI18N
        jLabelIniciarSesion.setText("Iniciar Sesion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabelIniciarSesion)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabelIniciarSesion)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabelNoCuenta.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabelNoCuenta.setText("¿No tienes una cuenta?");

        jButtonRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(153, 0, 153));
        jButtonRegistrar.setText("Registrate");
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabelNoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrar)
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoCuenta)
                    .addComponent(jButtonRegistrar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelUsuario.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");

        jLabelPassword.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabelPassword.setText("Contraseña");

        jTextFieldUsuario.setFont(new java.awt.Font("Roboto Thin", 2, 14)); // NOI18N
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jTextFieldPassword.setFont(new java.awt.Font("Roboto Thin", 2, 14)); // NOI18N
        jTextFieldPassword.setBorder(null);

        jButtonIngresar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonIngresar.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(153, 0, 153));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setBorderPainted(false);
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIngresar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPassword)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIngresar)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        VtnPrincipalSignUp objVtnPrincipalSignUp
                = new VtnPrincipalSignUp(this.objServAlmacUsuarios);
        objVtnPrincipalSignUp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objVtnPrincipalSignUp.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        boolean usuarioAutenticado, bandera;
        usuarioAutenticado = false;
        
        //Validar credenciales de inicio de sesion
        for (int i = 0; i < objServAlmacUsuarios.listarUsuarios().size(); i++) {
            boolean existeUsuario = this.objServAlmacUsuarios.listarUsuarios().get(i).getNombreUser().equals(jTextFieldUsuario.getText());
            if (existeUsuario) {
                boolean passOk = this.objServAlmacUsuarios.listarUsuarios().get(i).getPassword().equals(jTextFieldPassword.getText());
                if (passOk) {
                    usuarioAutenticado = true;
                    Utilidades.mensajeExito("Bienvenido " + jTextFieldUsuario.getText(), "Inicio de sesion exitoso");
                }
            }
        }
        //si el inicio de sesion es exitoso lanza la ventana correspondiente al rol, caso contrario lanza mensaje de error
        if (usuarioAutenticado) {
            VtnPrincipalAdmin objVtnPrincipalAdmin
                    = new VtnPrincipalAdmin();
            objVtnPrincipalAdmin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            objVtnPrincipalAdmin.setVisible(true);
        } else {
            Utilidades.mensajeError("Usuario o contraseña incrrectos", "Error de inicio de sesion");
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelNoCuenta;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
