/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.registroInicioSesion;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import co.edu.unicauca.mvc.vistas.organizadores.VtnPrincipalOrganizador;
//import co.edu.unicauca.mvc.vistas.adminConferencia.VtnPrincipalAdmin;
import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoUsuarios;
//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoConferencias;
//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoOrganizadores;
import co.edu.unicauca.mvc.modelos.Usuario;
import co.edu.unicauca.mvc.utilidades.Utilidades;
import javax.swing.border.MatteBorder;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Dark
 */
public class VtnPrincipalLogin extends javax.swing.JFrame {

    private ServicioAlmacenamientoUsuarios objServAlmacUsuarios;
    private ServicioAlmacenamientoConferencias objServAlmacConferencias;
    private ServicioAlmacenamientoArticulos objServAlmacArticulos;
    private VtnPrincipalSignUp objVtnPrincipalSignUp;

    /**
     * Creates new form VtnPrincipalLogin1
     */
    public VtnPrincipalLogin() {
        initComponents();
        MatteBorder bordeInferior = new MatteBorder(0, 0, 1, 0, Color.white);
        jTextFieldUsuario.setBorder(bordeInferior);
        jPasswordFieldContrasena.setBorder(bordeInferior);
    }

    public void asociarServicoAlmacenamientoUsuarios(ServicioAlmacenamientoUsuarios objServicio) {
        this.objServAlmacUsuarios = objServicio;
        relacionarInternalFrameConJdesptokPane();
    }
    
    public void asociarServicoAlmacenamientoConferencias(ServicioAlmacenamientoConferencias objServicio) {
        this.objServAlmacConferencias = objServicio;
        relacionarInternalFrameConJdesptokPane();
    }
    
    public void asociarServicoAlmacenamientoArticulos(ServicioAlmacenamientoArticulos objServicio) {
        this.objServAlmacArticulos = objServicio;
        relacionarInternalFrameConJdesptokPane();
    }  

    private void relacionarInternalFrameConJdesptokPane() {
        this.objVtnPrincipalSignUp = new VtnPrincipalSignUp(this.objServAlmacUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIniciarSesion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNoCuenta = new javax.swing.JLabel();
        jButtonRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelIniciarSesion.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        jLabelIniciarSesion.setForeground(new java.awt.Color(255, 0, 102));
        jLabelIniciarSesion.setText("Iniciar Sesion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNoCuenta.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jLabelNoCuenta.setText("¿No tienes una cuenta?");

        jButtonRegistrar.setFont(new java.awt.Font("Roboto Thin", 0, 14)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 0, 102));
        jButtonRegistrar.setText("Registrate");
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseEntered(evt);
            }
        });
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabelNoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrar)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoCuenta)
                    .addComponent(jButtonRegistrar))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));

        jLabelUsuario.setFont(new java.awt.Font("Roboto Condensed Light", 0, 15)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario");

        jLabelPassword.setFont(new java.awt.Font("Roboto Condensed Light", 0, 15)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña");

        jTextFieldUsuario.setBackground(new java.awt.Color(255, 0, 102));
        jTextFieldUsuario.setFont(new java.awt.Font("Roboto Condensed Light", 2, 15)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jButtonIngresar.setBackground(new java.awt.Color(255, 0, 102));
        jButtonIngresar.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonIngresar.setContentAreaFilled(false);
        jButtonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena.setBackground(new java.awt.Color(255, 0, 102));
        jPasswordFieldContrasena.setFont(new java.awt.Font("Roboto Condensed Light", 2, 15)); // NOI18N
        jPasswordFieldContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldContrasena.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        objVtnPrincipalSignUp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objVtnPrincipalSignUp.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        boolean usuarioAutenticado;
        usuarioAutenticado = false;

        //se quema un usuario por defecto para iniciar sesion rapidamente
        if (objServAlmacUsuarios.listarUsuarios().isEmpty()) {
            Usuario userDefecto = new Usuario("admin", "admin@correo.com", "1234", "Admin");
            objServAlmacUsuarios.registrarUsuario(userDefecto);
            System.out.println(objServAlmacUsuarios.listarUsuarios());
        }

        //Validar credenciales de inicio de sesion
        for (int i = 0; i < objServAlmacUsuarios.listarUsuarios().size(); i++) {
            boolean existeUsuario = this.objServAlmacUsuarios.listarUsuarios().get(i).getNombreUser().equals(jTextFieldUsuario.getText());
            if (existeUsuario) {
                boolean passOk = this.objServAlmacUsuarios.listarUsuarios().get(i).getPassword().equals(jPasswordFieldContrasena.getText());
                if (passOk) {
                    usuarioAutenticado = true;
                    Utilidades.mensajeExito("Bienvenido " + jTextFieldUsuario.getText(), "Inicio de sesion exitoso");
                }
            }
        }
        //si el inicio de sesion es exitoso lanza la ventana correspondiente al rol, caso contrario lanza mensaje de error
        if (usuarioAutenticado) {
            System.out.println("Estado 1: " + objServAlmacConferencias);
            VtnPrincipalOrganizador objVtnPrincipalOrganizador = new VtnPrincipalOrganizador();
            objVtnPrincipalOrganizador.asociarServiciosAlmacenamiento(objServAlmacConferencias, objServAlmacUsuarios,objServAlmacArticulos);
            objVtnPrincipalOrganizador.setVisible(true);
            System.out.println("Estado 2: " + objServAlmacConferencias);
        } else {
            Utilidades.mensajeError("Usuario o contraseña incorrectos", "Error de inicio de sesion");
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JLabel jLabelNoCuenta;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
