/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package co.edu.unicauca.mvc.vistas.adminConferencia;

import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;
import co.edu.unicauca.mvc.modelos.Articulo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class VtnVerEstadisticas extends javax.swing.JInternalFrame {

    public ServicioAlmacenamientoArticulos objServicio;
    /**
     * Creates new form VtnVerEstadisticas
     * @param objServicio
     */
    public VtnVerEstadisticas(ServicioAlmacenamientoArticulos objServicio) {
        initComponents();
        this.objServicio=objServicio;
    }

    public void limpiarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableStats.getModel();
        int filas = this.jTableStats.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }

    private void llenarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.jTableStats.getModel();
        limpiarTabla();
        ArrayList<Articulo> listaArticulos
                = (ArrayList<Articulo>) this.objServicio.listarArticulos();

        for (int i = 0; i < listaArticulos.size(); i++) {
            Object[] fila = {
                listaArticulos.get(i).getIdArticulo(),
                listaArticulos.get(i).getTitulo(),
                listaArticulos.get(i).getRevision().getResultado()};
            model.addRow(fila);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jButtonVerStats = new javax.swing.JButton();

        jLabelTitulo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        jLabelTitulo.setText("Estadisticas de la conferencia");

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Articulo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableStats);
        if (jTableStats.getColumnModel().getColumnCount() > 0) {
            jTableStats.getColumnModel().getColumn(0).setResizable(false);
        }

        jButtonVerStats.setBackground(new java.awt.Color(255, 0, 102));
        jButtonVerStats.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jButtonVerStats.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerStats.setText("VER ESTADISTICAS");
        jButtonVerStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonVerStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButtonVerStats, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelTitulo)
                .addGap(37, 37, 37)
                .addComponent(jButtonVerStats, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerStatsActionPerformed
        llenarTabla();
    }//GEN-LAST:event_jButtonVerStatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVerStats;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStats;
    // End of variables declaration//GEN-END:variables
}
